Upload libmozglue by itself

diff --git a/app/scripts/fetch_xulrunner b/app/scripts/fetch_xulrunner
--- a/app/scripts/fetch_xulrunner
+++ b/app/scripts/fetch_xulrunner
@@ -612,31 +612,50 @@ if [ $BUILD_MAC == 1 ]; then
 		hdiutil detach -quiet /Volumes/Firefox
 	fi
 	
-	# Download custom components (e.g., XUL), as an xz-compressed tarball of the MacOS folder with
-	# custom files in it
+	# Download and extract custom libmozglue.dylib
 	echo
-	rm -rf MacOS
-	if [ -n "$custom_components_hash_mac" ]; then
-		if [ -e "Firefox $GECKO_VERSION MacOS.zip" ]; then
-			echo "Using Firefox $GECKO_VERSION MacOS.zip"
-			unzip "Firefox $GECKO_VERSION MacOS.zip"
+	hash="$custom_components_hash_mac"
+	if [ -n "$hash" ]; then
+		xzfile="Firefox $GECKO_VERSION libmozglue.dylib.xz"
+		# Filename doesn't include "esr"
+		url="${custom_components_url}mac/${GECKO_VERSION//esr}-libmozglue-$hash.dylib.xz"
+
+		if [[ "$(uname)" = "Darwin" ]]; then
+			shasum="shasum -a 256"
 		else
-			echo "Downloading custom Firefox components"
-			echo
-			curl -o MacOS.tar.xz "${custom_components_url}mac/$custom_components_hash_mac.tar.xz"
-			
-			# Verify hash
-			if [[ "`uname`" = "Darwin" ]]; then
-				shasum="shasum -a 256"
-			else
-				shasum=sha256sum
-			fi
-			echo
-			echo "$custom_components_hash_mac  MacOS.tar.xz" | $shasum -c -
-			echo
-			
-			tar xvf MacOS.tar.xz
+			shasum=sha256sum
 		fi
+
+		download_xz() {
+			echo "Downloading custom libmozglue.dylib"
+			echo
+			echo $url
+			curl -fo "$xzfile" "$url"
+		}
+
+		verify_hash() {
+			echo "$hash  $xzfile" | $shasum -c -
+		}
+
+		# Download if file doesn't exist
+		if [ ! -e "$xzfile" ]; then
+			download_xz
+		fi
+
+		echo
+		if ! verify_hash; then
+			echo "SHA hash mismatch. Redownloading libmozglue.dylib…"
+			rm -f "$xzfile"
+			download_xz
+			echo
+			if ! verify_hash; then
+				echo "Hash still doesn't match. Aborting."
+				exit 1
+			fi
+		fi
+		echo
+
+		xz -d --stdout "$xzfile" > Firefox.app/Contents/MacOS/libmozglue.dylib
 		echo
 	fi
 	
